dataset:
  name : 'NuScenes'
  type : 'RangeImg'
  root :
      train : 'E:\Research\Datasets\range_img\range\'
      val : 'E:\Research\Datasets\range_img_val_v2\' # 'E:\Research\Datasets\range_img_val'
      test : 'E:\Research\Datasets\range_img_val'
  mean:
    - 12.1063
    - 7.7884
    - -0.3015
    - -0.3165
    - -0.7672
  std:
    - 19.4655
    - 12.2054
    - 9.5711
    - 10.7408
    - 1.5764

  class_names :
    - 'ignore'
    - 'car'
    - 'pedestrian'
    - 'bicycle'
    - 'motorcycle'
    - 'bus'
    - 'truck'
    - 'construction_vehicle'
    - 'trailer'
    - 'barrier'
    - 'traffic_cone'
    - 'driveable_surface'
    - 'other_flat'
    - 'sidewalk'
    - 'terrain'
    - 'manmade'
    - 'vegetation'

  ignore_class: 0

  class_counts :
      - 1.6149e+09
      - 1.5331e+08
      - 1.3790e+07
      - 8.1859e+06
      - 1.9989e+07
      - 3.1068e+07
      - 6.9388e+07
      - 2.4461e+07
      - 2.9413e+07
      - 7.9546e+07
      - 1.1217e+07
      - 1.0160e+09
      - 2.8585e+07
      - 1.9434e+08
      - 1.7599e+08
      - 4.7516e+08
      - 3.0121e+08

  learning_map:
    0: 0
    1: 0
    2: 2
    3: 2
    4: 2
    5: 0
    6: 2
    7: 0
    8: 0
    9: 9
    10: 0
    11: 0
    12: 10
    13: 0
    14: 3
    15: 5
    16: 5
    17: 1
    18: 7
    19: 0
    20: 0
    21: 4
    22: 8
    23: 6
    24: 11
    25: 12
    26: 13
    27: 14
    28: 15
    29: 0
    30: 16
    31: 0

  learning_map_inv:
    0: 0 # 'ignore'
    1: 17 # 'car'
    2: 2 # 'pedestrian'
    3: 14 # 'bicycle'
    4: 21 # 'motorcycle'
    5: 16 # 'bus'
    6: 23 # 'truck'
    7: 18 # 'construction_vehicle'
    8: 22 # 'trailer'
    9: 9 # 'barrier'
    10: 12 # 'traffic_cone'
    11: 24 # 'driveable_surface'
    12: 25 # 'other_flat'
    13: 26 # 'sidewalk'
    14: 27 # 'terrain'
    15: 28 # 'manmade'
    16: 30 # 'vegetation'

  epsilon : 0.001

  n_channels: 5
  n_classes: 17

  color_map:
    0: [ 0,0,0 ]
    1: [ 255,158,0 ]
    2: [ 0,0,230 ]
    3: [ 220,20,60 ]
    4: [ 135,206,235 ]
    5: [ 255,69,0 ]
    6: [ 255,99,71 ]
    7: [ 188,143,143 ]
    8: [ 255,228,196 ]
    9: [ 112,128,144 ]
    10: [ 47,79,79 ]
    11: [ 0,207,191 ]
    12: [ 175,0,75 ]
    13: [ 75,0,75 ]
    14: [ 112,180,60 ]
    15: [ 222,184,135 ]
    16: [ 0,175,0 ]


train:
  model : 'DLA_ATTN_NET'
  gpus : -1
  strategy : null # ddp for multi-gpus
  batch_size : 4
  workers : 2
  max_epochs : 1000
  shuffle : True
  logging: True # data will be logged to wandb and the checkpoints will be saved
  log_dir: 'E:\source_code\checkpoints\' # checkpoints will be saved here
  wandb_log_proj : 'DLA_v1'
  pretrained_dir : 'D:\saved_model_ablation\aug_attn_wasl\2023_2_20_10_50_57_epoch=7_val_miou=0.769272_aug=True.ckpt'
  # 'D:\saved_model_ablation\aug_attn_wasl\2023_2_20_10_50_57_epoch=7_val_miou=0.769272_aug=True.ckpt'
  # 'D:\saved_model_ablation\baseline_dla\checkpoints\2023_2_16_13_0_57_epoch=27_val_miou=0.540288_aug=False.ckpt'
validate:
  model: 'DLA_ATTN_NET'
  gpus: -1
  strategy: null # ddp for multi-gpus
  batch_size: 1 # should be 1 for correct evaluation
  workers: 2
  shuffle: False
  logging: True # data will be logged to wandb and the checkpoints will be saved
  wandb_log_proj: 'DLA_val'
  pretrained_dir: 'D:\saved_model_ablation\aug_attn_wasl\2023_2_20_10_50_57_epoch=7_val_miou=0.769272_aug=True.ckpt'

test:
  gpus: -1
  strategy: null
  batch_size: 1
  workers: 2
  shuffle: True
  logging : True
  wandb_log_proj : 'DLA_val'
  saved_checkpoint : 'D:\saved_model_ablation\aug_attn_wasl\2023_2_20_10_50_57_epoch=7_val_miou=0.769272_aug=True.ckpt'

post_process:
  apply : True
  knn : 5
  search : 5
  sigma : 1.0
  cutoff : 1.0
  IsGauss : True